aset/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "aset"

urlpatterns = [
    path('read/', views.read_aset, name='read_aset'),
    path('read/dekorasi/', views.read_dekorasi, name='read_dekorasi'),
    path('read/bibit-tanaman/', views.read_bibit_tanaman, name='read_bibit_tanaman'),
    path('read/hewan/', views.read_hewan, name='read_hewan'),
    path('read/kandang/', views.read_kandang, name='read_kandang'),
    path('read/alat-produksi/', views.read_alat_produksi, name='read_alat_produksi'),
    path('read/petak-sawah/', views.read_petak_sawah, name='read_petak_sawah'),
    path('create/', views.create_aset, name='create_aset'),
    path('create/dekorasi/', views.create_dekorasi, name='create_dekorasi'),
    path('create/bibit-tanaman/', views.create_bibit_tanaman, name='create_bibit_tanaman'),
    path('create/hewan/', views.create_hewan, name='create_hewan'),
    path('create/kandang/', views.create_kandang, name='create_kandang'),
    path('create/alat-produksi/', views.create_alat_produksi, name='create_alat_produksi'),
    path('create/petak-sawah/', views.create_petak_sawah, name='create_petak_sawah'),
    path('form_update_dekorasi/<str:id>/', views.formUpdateDekorasi, name='formUpdateDekorasi'),
    path('update/dekorasi/', views.updateDekorasi, name='updateDekorasi'),
    path('form_update_bibit_tanaman/<str:id>/', views.formUpdateBibitTanaman, name='formUpdateBibitTanaman'),
    path('update/bibit-tanaman/', views.updateBibitTanaman, name='updateBibitTanaman'),
    path('form_update_kandang/<str:id>/', views.formUpdateKandang, name='formUpdateKandang'),
    path('update/kandang/', views.updateKandang, name='updateKandang'),
    path('form_update_hewan/<str:id>/', views.formUpdateHewan, name='formUpdateHewan'),
    path('update/hewan/', views.updateHewan, name='updateHewan'),
    path('form_update_alat_produksi/<str:id>/', views.formUpdateAlatProduksi, name='formUpdateAlatProduksi'),
    path('update/alat-produksi/', views.updateAlatProduksi, name='updateAlatProduksi'),
    path('form_update_petak_sawah/<str:id>/', views.formUpdatePetakSawah, name='formUpdatePetakSawah'),
    path('delete/dekorasi/<str:id>/', views.deleteDekorasi, name='deleteDekorasi'),
    path('delete/bibit-tanaman/<str:id>/', views.deleteBibitTanaman, name='deleteBibitTanaman'),
    path('delete/kandang/<str:id>/', views.deleteKandang, name='deleteKandang'),
    path('delete/hewan/<str:id>/', views.deleteHewan, name='deleteHewan'),
    path('delete/alat-produksi/<str:id>/', views.deleteAlatProduksi, name='deleteAlatProduksi'),
    path('delete/petak-sawah/<str:id>/', views.deletePetakSawah, name='deletePetakSawah'),
]

koleksi_aset/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "koleksi_aset"

urlpatterns = [
    path('read/', views.read_koleksi_aset, name='read_koleksi_aset'),
    path('dekorasi/', views.dekorasi, name='dekorasi'),
    path('bibit-tanaman/', views.bibit_tanaman, name='bibit_tanaman'),
    path('kandang/', views.kandang, name='kandang'),
    path('hewan/', views.hewan, name='hewan'),
    path('alat-produksi/', views.alat_produksi, name='alat_produksi'),
    path('petak-sawah/', views.petak_sawah, name='petak_sawah'),
]

produk/urls.py
from django.urls import path

from .views import viewsProduk,viewsProduksi,viewsHistoriProduksiMakanan, createProduk, updateProduk, formUpdateProduk, deleteProduk, createProduksi,deleteProduksi

app_name ='produk'

urlpatterns = [
    path('form_create_produk/', createProduk, name='createProduk'),
    path('read_produk/', viewsProduk, name='produk'),
    path('form_update_produk/<str:id>/', formUpdateProduk, name='formUpdateProduk'),
    path('update_produk/', updateProduk, name='updateProduk'),   
    path('delete_produk/<str:id>/', deleteProduk, name='deleteProduk'), 
     
    path('form_create_produksi/', createProduksi, name='createProduksi'),
    path('read_produksi/', viewsProduksi, name='produksi'),
    # path('form_update_produksi/<str:id>/', formUpdateProduksi, name='formUpdateProduksi'),
    # path('update_produk/', updateProduksi, name='updateProduksi'),
    path('delete_produksi/<str:id>/', deleteProduksi, name='deleteProduksi'),
    
    # path('form_create_histori_produksi_makanan/', createHistoriProduksiMakanan, name='createHistoriProduksiMakanan'),
    path('read_histori_produksi_makanan/', viewsHistoriProduksiMakanan, name='historiProduksiMakanan'),
    
]

tk_e06/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('aset/', include('aset.urls')),
    path('koleksi-aset/', include('koleksi_aset.urls')),
    path('transaksi-pembelian/', include('transaksi_pembelian.urls')),
    path('paket-koin/', include('paket_koin.urls')),
    path('lumbung/', include('lumbung.urls')),
    path('produk/', include('produk.urls')),
    path('', include('histori.urls')),
]

koleksi_aset/models.py
from django.db import models

# Create your models here.

koleksi_aset/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.db import connection
from collections import namedtuple
from login.views import namedtuplefetchall, cekRole

def read_koleksi_aset(request):
    return render(request, 'koleksi_aset.html')

def dekorasi(request):
    cursor = connection.cursor()
    cursor.execute("set search_path to public")
    try:
        Role = request.session['role']
    except:
        return redirect('/')
    cursor.execute("set search_path to hiday")
    cursor.execute(f"select email, a.nama, a.minimum_level, a.harga_beli, kama.jumlah from dekorasi d, koleksi_aset ka, aset a, koleksi_aset_memiliki_aset kama where d.id_aset = a.id and kama.id_koleksi_aset = ka.email and kama.id_aset = a.id")
    hasil = namedtuplefetchall(cursor)

    roleAdmin = False
    rolePengguna = False

    if Role == "Admin":
        roleAdmin = True
    elif Role == "Pengguna":
        rolePengguna = True
    
    data = {
        'list_koleksi_dekorasi' : hasil,
        'roleAdmin' : roleAdmin,
        'rolePengguna' : rolePengguna,
    }

    return render(request, "dekorasi.html", data) 

def bibit_tanaman(request):
    cursor = connection.cursor()
    cursor.execute("set search_path to public")
    try:
        Role = request.session['role']
    except:
        return redirect('/')
    cursor.execute("set search_path to hiday")
    cursor.execute(f"select email, a.nama, a.minimum_level, a.harga_beli, kama.jumlah from bibit_tanaman bt, koleksi_aset ka, aset a, koleksi_aset_memiliki_aset kama where bt.id_aset = a.id and kama.id_koleksi_aset = ka.email and kama.id_aset = a.id")
    hasil = namedtuplefetchall(cursor)

    roleAdmin = False
    rolePengguna = False

    if Role == "Admin":
        roleAdmin = True
    elif Role == "Pengguna":
        rolePengguna = True

    data = {
        'list_koleksi_bibit_tanaman' : hasil,
        'roleAdmin' : roleAdmin,
        'rolePengguna' : rolePengguna,
    }

    return render(request, "bibit_tanaman.html", data)

def kandang(request):
    cursor = connection.cursor()
    cursor.execute("set search_path to public")
    try:
        Role = request.session['role']
    except:
        return redirect('/')
    cursor.execute("set search_path to hiday")
    cursor.execute(f"select email, a.nama, a.minimum_level, a.harga_beli, kama.jumlah from kandang k, koleksi_aset ka, aset a, koleksi_aset_memiliki_aset kama where k.id_aset = a.id and kama.id_koleksi_aset = ka.email and kama.id_aset = a.id")
    hasil = namedtuplefetchall(cursor)

    roleAdmin = False
    rolePengguna = False

    if Role == "Admin":
        roleAdmin = True
    elif Role == "Pengguna":
        rolePengguna = True

    data = {
        'list_koleksi_kandang' : hasil,
        'roleAdmin' : roleAdmin,
        'rolePengguna' : rolePengguna,
    }

    return render(request, "kandang.html", data)

def hewan(request):
    cursor = connection.cursor()
    cursor.execute("set search_path to public")
    try:
        Role = request.session['role']
    except:
        return redirect('/')
    cursor.execute("set search_path to hiday")
    cursor.execute(f"select email, a.nama, a.minimum_level, a.harga_beli, kama.jumlah from hewan h, koleksi_aset ka, aset a, koleksi_aset_memiliki_aset kama where h.id_aset = a.id and kama.id_koleksi_aset = ka.email and kama.id_aset = a.id")
    hasil = namedtuplefetchall(cursor)

    roleAdmin = False
    rolePengguna = False

    if Role == "Admin":
        roleAdmin = True
    elif Role == "Pengguna":
        rolePengguna = True

    data = {
        'list_koleksi_hewan' : hasil,
        'roleAdmin' : roleAdmin,
        'rolePengguna' : rolePengguna,
    }

    return render(request, "hewan.html", data)

def alat_produksi(request):
    cursor = connection.cursor()
    cursor.execute("set search_path to public")
    try:
        Role = request.session['role']
    except:
        return redirect('/')
    cursor.execute("set search_path to hiday")
    cursor.execute(f"select email, a.nama, a.minimum_level, a.harga_beli, kama.jumlah from alat_produksi ap, koleksi_aset ka, aset a, koleksi_aset_memiliki_aset kama where ap.id_aset = a.id and kama.id_koleksi_aset = ka.email and kama.id_aset = a.id")
    hasil = namedtuplefetchall(cursor)

    roleAdmin = False
    rolePengguna = False

    if Role == "Admin":
        roleAdmin = True
    elif Role == "Pengguna":
        rolePengguna = True
    
    data = {
        'list_koleksi_alat_produksi' : hasil,
        'roleAdmin' : roleAdmin,
        'rolePengguna' : rolePengguna,
    }

    return render(request, "alat_produksi.html", data)

def petak_sawah(request):
    cursor = connection.cursor()
    cursor.execute("set search_path to public")
    try:
        Role = request.session['role']
    except:
        return redirect('/')
    cursor.execute("set search_path to hiday")
    cursor.execute(f"select email, a.nama, a.minimum_level, a.harga_beli, kama.jumlah from petak_sawah ps, koleksi_aset ka, aset a, koleksi_aset_memiliki_aset kama where ps.id_aset = a.id and kama.id_koleksi_aset = ka.email and kama.id_aset = a.id")
    hasil = namedtuplefetchall(cursor)

    roleAdmin = False
    rolePengguna = False

    if Role == "Admin":
        roleAdmin = True
    elif Role == "Pengguna":
        rolePengguna = True
    
    data = {
        'list_koleksi_petak_sawah' : hasil,
        'roleAdmin' : roleAdmin,
        'rolePengguna' : rolePengguna,
    }

    return render(request, "petak_sawah.html", data)

koleksi_aset/templates/alat_produksi.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Produk
{% endblock title %}


{% block content %}
<div class="container justify-content-center align-items-center">
    <h1 class="list_title">List Alat Produksi</h1>
    <h2 class="message">{{message}}</h2>

    <div class="row justify-content-center">
        <!-- {% if roleAdmin%}
        <a href="{% url 'produk:createProduk' %}" class="mybutton" role="button" style="margin-bottom: 30px;">Create Item</a>
        {% endif %}  -->
        <table class="table table-hover table-striped text-center">
            <thead>
                <tr>
                    <th scope="col">No</th>
                    {% if roleAdmin %}
                        <th scope="col">Email</th>
                    {% endif %} 
                    <th scope="col">Nama Aset</th>
                    <th scope="col">Minimum Level</th>
                    <th scope="col">Harga Beli</th>
                    <th scope="col">Jumlah</th>
                </tr>
            </thead>
            <tbody>
            {%for row in list_koleksi_alat_produksi %}
                <tr class="table-striped">
                    <th scope="row">{{forloop.counter}}</th>
                    {% if roleAdmin %}
                        <td>{{row.email}}</td>
                    {% endif %}
                    <td>{{row.nama}}</td>
                    <td>{{row.minimum_level}}</td>
                    <td>{{row.harga_beli}}</td>
                    <td>{{row.jumlah}}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table> 
    </div>
</div>
{% endblock content %}

koleksi_aset/templates/bibit_tanaman.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Produk
{% endblock title %}


{% block content %}
<div class="container justify-content-center align-items-center">
    <h1 class="list_title">List Bibit Tanaman</h1>
    <h2 class="message">{{message}}</h2>

    <div class="row justify-content-center">
        <!-- {% if roleAdmin%}
        <a href="{% url 'produk:createProduk' %}" class="mybutton" role="button" style="margin-bottom: 30px;">Create Item</a>
        {% endif %}  -->
        <table class="table table-hover table-striped text-center">
            <thead>
                <tr>
                    <th scope="col">No</th>
                    {% if roleAdmin %}
                        <th scope="col">Email</th>
                    {% endif %} 
                    <th scope="col">Nama Aset</th>
                    <th scope="col">Minimum Level</th>
                    <th scope="col">Harga Beli</th>
                    <th scope="col">Jumlah</th>
                </tr>
            </thead>
            <tbody>
            {%for row in list_koleksi_bibit_tanaman %}
                <tr class="table-striped">
                    <th scope="row">{{forloop.counter}}</th>
                    {% if roleAdmin %}
                        <td>{{row.email}}</td>
                    {% endif %}
                    <td>{{row.nama}}</td>
                    <td>{{row.minimum_level}}</td>
                    <td>{{row.harga_beli}}</td>
                    <td>{{row.jumlah}}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table> 
    </div>
</div>
{% endblock content %}

koleksi_aset/templates/dekorasi.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Produk
{% endblock title %}


{% block content %}
<div class="container justify-content-center align-items-center">
    <h1 class="list_title">List Dekorasi</h1>
    <h2 class="message">{{message}}</h2>

    <div class="row justify-content-center">
        <!-- {% if roleAdmin%}
        <a href="{% url 'produk:createProduk' %}" class="mybutton" role="button" style="margin-bottom: 30px;">Create Item</a>
        {% endif %}  -->
        <table class="table table-hover table-striped text-center">
            <thead>
                <tr>
                    <th scope="col">No</th>
                    {% if roleAdmin %}
                        <th scope="col">Email</th>
                    {% endif %} 
                    <th scope="col">Nama Aset</th>
                    <th scope="col">Minimum Level</th>
                    <th scope="col">Harga Beli</th>
                    <th scope="col">Jumlah</th>
                </tr>
            </thead>
            <tbody>
            {%for row in list_koleksi_dekorasi %}
                <tr class="table-striped">
                    <th scope="row">{{forloop.counter}}</th>
                    {% if roleAdmin %}
                        <td>{{row.email}}</td>
                    {% endif %}
                    <td>{{row.nama}}</td>
                    <td>{{row.minimum_level}}</td>
                    <td>{{row.harga_beli}}</td>
                    <td>{{row.jumlah}}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table> 
    </div>
</div>
{% endblock content %}

koleksi_aset/templates/hewan.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Produk
{% endblock title %}


{% block content %}
<div class="container justify-content-center align-items-center">
    <h1 class="list_title">List Hewan</h1>
    <h2 class="message">{{message}}</h2>

    <div class="row justify-content-center">
        <!-- {% if roleAdmin%}
        <a href="{% url 'produk:createProduk' %}" class="mybutton" role="button" style="margin-bottom: 30px;">Create Item</a>
        {% endif %}  -->
        <table class="table table-hover table-striped text-center">
            <thead>
                <tr>
                    <th scope="col">No</th>
                    {% if roleAdmin %}
                        <th scope="col">Email</th>
                    {% endif %} 
                    <th scope="col">Nama Aset</th>
                    <th scope="col">Minimum Level</th>
                    <th scope="col">Harga Beli</th>
                    <th scope="col">Jumlah</th>
                </tr>
            </thead>
            <tbody>
            {%for row in list_koleksi_hewan %}
                <tr class="table-striped">
                    <th scope="row">{{forloop.counter}}</th>
                    {% if roleAdmin %}
                        <td>{{row.email}}</td>
                    {% endif %}
                    <td>{{row.nama}}</td>
                    <td>{{row.minimum_level}}</td>
                    <td>{{row.harga_beli}}</td>
                    <td>{{row.jumlah}}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table> 
    </div>
</div>
{% endblock content %}

koleksi_aset/templates/kandang.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Produk
{% endblock title %}


{% block content %}
<div class="container justify-content-center align-items-center">
    <h1 class="list_title">List Kandang</h1>
    <h2 class="message">{{message}}</h2>

    <div class="row justify-content-center">
        <!-- {% if roleAdmin%}
        <a href="{% url 'produk:createProduk' %}" class="mybutton" role="button" style="margin-bottom: 30px;">Create Item</a>
        {% endif %}  -->
        <table class="table table-hover table-striped text-center">
            <thead>
                <tr>
                    <th scope="col">No</th>
                    {% if roleAdmin %}
                        <th scope="col">Email</th>
                    {% endif %} 
                    <th scope="col">Nama Aset</th>
                    <th scope="col">Minimum Level</th>
                    <th scope="col">Harga Beli</th>
                    <th scope="col">Jumlah</th>
                </tr>
            </thead>
            <tbody>
            {%for row in list_koleksi_kandang %}
                <tr class="table-striped">
                    <th scope="row">{{forloop.counter}}</th>
                    {% if roleAdmin %}
                        <td>{{row.email}}</td>
                    {% endif %}
                    <td>{{row.nama}}</td>
                    <td>{{row.minimum_level}}</td>
                    <td>{{row.harga_beli}}</td>
                    <td>{{row.jumlah}}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table> 
    </div>
</div>
{% endblock content %}

koleksi_aset/templates/koleksi_aset.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Read Koleksi Aset
{% endblock title %}

{% block content %}
<head>
  <meta charset="UTF-8">
    <title>HI DAY | Lihat Koleksi Aset
    </title>
</head>
<body>
<h1 class="list_title">Menu Lihat Koleksi Aset</h1>
<div class="container justify-content-center align-items-center">
  <div style="text-align:center">
    <a class="btn btn-primary" style="margin:10px;" href="{% url 'koleksi_aset:dekorasi' %}">Dekorasi</a>
  </div>
  <div style="text-align:center">
    <a class="btn btn-primary" style="margin:10px;" href="{% url 'koleksi_aset:bibit_tanaman' %}">Bibit Tanaman</a>
  </div>
  <div style="text-align:center">
    <a class="btn btn-primary" style="margin:10px;" href="{% url 'koleksi_aset:kandang' %}">Kandang</a>
  </div>
  <div style="text-align:center">
    <a class="btn btn-primary" style="margin:10px;" href="{% url 'koleksi_aset:hewan' %}">Hewan</a>
  </div>
  <div style="text-align:center">
    <a class="btn btn-primary" style="margin:10px;" href="{% url 'koleksi_aset:alat_produksi' %}">Alat Produksi</a>
  </div>
  <div style="text-align:center">
    <a class="btn btn-primary"style="margin:10px;" href="{% url 'koleksi_aset:petak_sawah' %}">Petak Sawah</a>
  </div>
</div>
</body>
{% endblock content %}

koleksi_aset/templates/petak_sawah.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Produk
{% endblock title %}


{% block content %}
<div class="container justify-content-center align-items-center">
    <h1 class="list_title">List Petak Sawah</h1>
    <h2 class="message">{{message}}</h2>

    <div class="row justify-content-center">
        <!-- {% if roleAdmin%}
        <a href="{% url 'produk:createProduk' %}" class="mybutton" role="button" style="margin-bottom: 30px;">Create Item</a>
        {% endif %}  -->
        <table class="table table-hover table-striped text-center">
            <thead>
                <tr>
                    <th scope="col">No</th>
                    {% if roleAdmin %}
                        <th scope="col">Email</th>
                    {% endif %} 
                    <th scope="col">Nama Aset</th>
                    <th scope="col">Minimum Level</th>
                    <th scope="col">Harga Beli</th>
                    <th scope="col">Jumlah</th>
                </tr>
            </thead>
            <tbody>
            {%for row in list_koleksi_petak_sawah %}
                <tr class="table-striped">
                    <th scope="row">{{forloop.counter}}</th>
                    {% if roleAdmin %}
                        <td>{{row.email}}</td>
                    {% endif %}
                    <td>{{row.nama}}</td>
                    <td>{{row.minimum_level}}</td>
                    <td>{{row.harga_beli}}</td>
                    <td>{{row.jumlah}}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table> 
    </div>
</div>
{% endblock content %}