aset/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "aset"

urlpatterns = [
    path('read/', views.read_aset, name='read_aset'),
    path('read/dekorasi/', views.read_dekorasi, name='read_dekorasi'),
    path('read/bibit-tanaman/', views.read_bibit_tanaman, name='read_bibit_tanaman'),
    path('read/hewan/', views.read_hewan, name='read_hewan'),
    path('read/kandang/', views.read_kandang, name='read_kandang'),
    path('read/alat-produksi/', views.read_alat_produksi, name='read_alat_produksi'),
    path('read/petak-sawah/', views.read_petak_sawah, name='read_petak_sawah'),
    path('create/', views.create_aset, name='create_aset'),
    path('create/dekorasi/', views.create_dekorasi, name='create_dekorasi'),
    path('create/bibit-tanaman/', views.create_bibit_tanaman, name='create_bibit_tanaman'),
    path('create/hewan/', views.create_hewan, name='create_hewan'),
    path('create/kandang/', views.create_kandang, name='create_kandang'),
    path('create/alat-produksi/', views.create_alat_produksi, name='create_alat_produksi'),
    path('create/petak-sawah/', views.create_petak_sawah, name='create_petak_sawah'),
    path('form_update_dekorasi/<str:id>/', views.formUpdateDekorasi, name='formUpdateDekorasi'),
    path('update/dekorasi/', views.updateDekorasi, name='updateDekorasi'),
    path('form_update_bibit_tanaman/<str:id>/', views.formUpdateBibitTanaman, name='formUpdateBibitTanaman'),
    path('update/bibit-tanaman/', views.updateBibitTanaman, name='updateBibitTanaman'),
    path('form_update_kandang/<str:id>/', views.formUpdateKandang, name='formUpdateKandang'),
    path('update/kandang/', views.updateKandang, name='updateKandang'),
    path('form_update_hewan/<str:id>/', views.formUpdateHewan, name='formUpdateHewan'),
    path('update/hewan/', views.updateHewan, name='updateHewan'),
    path('form_update_alat_produksi/<str:id>/', views.formUpdateAlatProduksi, name='formUpdateAlatProduksi'),
    path('update/alat-produksi/', views.updateAlatProduksi, name='updateAlatProduksi'),
    path('form_update_petak_sawah/<str:id>/', views.formUpdatePetakSawah, name='formUpdatePetakSawah'),
    path('delete/dekorasi/<str:id>/', views.deleteDekorasi, name='deleteDekorasi'),
    path('delete/bibit-tanaman/<str:id>/', views.deleteBibitTanaman, name='deleteBibitTanaman'),
    path('delete/kandang/<str:id>/', views.deleteKandang, name='deleteKandang'),
    path('delete/hewan/<str:id>/', views.deleteHewan, name='deleteHewan'),
    path('delete/alat-produksi/<str:id>/', views.deleteAlatProduksi, name='deleteAlatProduksi'),
    path('delete/petak-sawah/<str:id>/', views.deletePetakSawah, name='deletePetakSawah'),
]

koleksi_aset/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "koleksi_aset"

urlpatterns = [
    path('read/', views.read_koleksi_aset, name='read_koleksi_aset'),
    path('dekorasi/', views.dekorasi, name='dekorasi'),
    path('bibit-tanaman/', views.bibit_tanaman, name='bibit_tanaman'),
    path('kandang/', views.kandang, name='kandang'),
    path('hewan/', views.hewan, name='hewan'),
    path('alat-produksi/', views.alat_produksi, name='alat_produksi'),
    path('petak-sawah/', views.petak_sawah, name='petak_sawah'),
]

login/urls.py
from django.contrib import admin
from django.urls import path

from .views import index, login, register, registerPenggunaRole, insertAdmin, profil, logout, insertPengguna, lihatIsiLumbung

app_name = 'authentication'

urlpatterns = [
    path('', index, name='index'),
    path('Profil/', profil, name='profil'),
    path('LihatIsiLumbung/', lihatIsiLumbung, name='lihatIsiLumbung'),
    path('Logout/', logout,  name='logout'),
    path('Home/', login, name='home'),
    path('Register/', register),
    path('RegisterRole/', registerPenggunaRole),
    path('insertAdmin/', insertAdmin),
    path('insertPengguna/', insertPengguna),
    
]

lumbung/urls.py
from django.contrib import admin
from django.urls import path
from .views import produksi_tanaman, transaksi_upgrade_lumbung, histori_produksi_tanaman, upgrade_lumbung

urlpatterns = [
    path('transaksi-upgrade-lumbung/', transaksi_upgrade_lumbung, name='transaksi-upgrade-lumbung'),
    path('histori-produksi-tanaman/', histori_produksi_tanaman, name='histori-produksi-tanaman'),
    path('upgrade-lumbung/', upgrade_lumbung, name='upgrade-lumbung'),
    path('produksi-tanaman/', produksi_tanaman, name='produksi-tanaman'),
]

produk/urls.py
from django.urls import path

from .views import viewsProduk,viewsProduksi,viewsHistoriProduksiMakanan, createProduk, updateProduk, formUpdateProduk, deleteProduk, createProduksi,deleteProduksi

app_name ='produk'

urlpatterns = [
    path('form_create_produk/', createProduk, name='createProduk'),
    path('read_produk/', viewsProduk, name='produk'),
    path('form_update_produk/<str:id>/', formUpdateProduk, name='formUpdateProduk'),
    path('update_produk/', updateProduk, name='updateProduk'),   
    path('delete_produk/<str:id>/', deleteProduk, name='deleteProduk'), 
     
    path('form_create_produksi/', createProduksi, name='createProduksi'),
    path('read_produksi/', viewsProduksi, name='produksi'),
    # path('form_update_produksi/<str:id>/', formUpdateProduksi, name='formUpdateProduksi'),
    # path('update_produk/', updateProduksi, name='updateProduksi'),
    path('delete_produksi/<str:id>/', deleteProduksi, name='deleteProduksi'),
    
    # path('form_create_histori_produksi_makanan/', createHistoriProduksiMakanan, name='createHistoriProduksiMakanan'),
    path('read_histori_produksi_makanan/', viewsHistoriProduksiMakanan, name='historiProduksiMakanan'),
    
]

tk_e06/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('aset/', include('aset.urls')),
    path('koleksi-aset/', include('koleksi_aset.urls')),
    path('transaksi-pembelian/', include('transaksi_pembelian.urls')),
    path('paket-koin/', include('paket_koin.urls')),
    path('lumbung/', include('lumbung.urls')),
    path('produk/', include('produk.urls')),
    path('', include('histori.urls')),
]

transaksi_pembelian/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "transaksi_pembelian"

urlpatterns = [
    path('read/', views.read_transaksi_pembelian_aset, name='read_transaksi_pembelian_aset'),
    path('create/', views.create_transaksi_pembelian_aset, name='create_transaksi_pembelian_aset'),

]

login/forms.py
from django import forms

class LoginForm(forms.Form):
    email = forms.CharField(label = 'Email', max_length=50)
    password = forms.CharField(label = 'Password',  widget=forms.PasswordInput, max_length=128)

class ChoiceRoleForm(forms.Form):
    CHOICES=[
        ('Admin','Admin'),
        ('Pengguna','Pengguna')]
    Role = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect)

class AdminRoleForm(forms.Form):
    email = forms.CharField(label = 'Email' , max_length=50)
    password = forms.CharField(label = 'Password',  widget=forms.PasswordInput, max_length=128)

class PenggunaRoleForm(forms.Form):
    email = forms.CharField(label = 'Email', max_length=50)
    password = forms.CharField(label = 'Password',  widget=forms.PasswordInput, max_length=128)
    nama_area_pertanian = forms.CharField(label = 'nama_area_pertanian', max_length=50)

login/views.py
from django.shortcuts import render, redirect
from .forms import LoginForm, ChoiceRoleForm, AdminRoleForm, PenggunaRoleForm
from django.db import connection
from collections import namedtuple


def namedtuplefetchall(cursor):
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def index(request, validasi = None):
    try:
        email = request.session['email']
        return login(request)
    except KeyError:
        formulir = LoginForm()
        message = ""
        if(validasi==False):
            message = "Invalid email or password"
        argument = { 
            'formlogin' : formulir,
            'message' : message
        }
        return render(request, 'login.html', argument)
    
def login(request):
    try:
        email = request.session['email']
        password = request.session['password']
    except:
        email = request.POST['email']
        password = request.POST['password']

    email = str(email)
    password = str(password)
    cursor = connection.cursor()
    cursor.execute("set search_path to hiday")
    cursor.execute("""select result.email, result.password
                        from akun, (
                        select email, password
                        from pengguna
                        union
                        select email, password
                        from admin
                        ) as result
                        where akun.email = result.email and  result.email='"""+email+"' and result.password='"+password+"'")
     
    hasil = namedtuplefetchall(cursor)
    role = cekRole(email)
    roleAdmin = False
    rolePengguna = False
    if (role == 'Admin'):
        roleAdmin = True
    if (role == 'Pengguna'):
        rolePengguna = True

    cursor.execute("set search_path to public")
    if (hasil == []):
        cursor.close()
        return index(request, False)
    else:
        request.session['email'] = hasil[0].email
        request.session['password'] = hasil[0].password
        request.session.set_expiry(1800)
        request.session['role'] = role
        argument = {
            'nama_akun' : email.split("@", 1)[0],
            'email' : email,
            'roleAdmin' : roleAdmin,
            'rolePengguna' : rolePengguna
        }
        cursor.close()
        return render(request, "home.html", argument)

def logout(request):
    request.session.flush()
    request.session.clear_expired()
    return index(request)

def profil(request):
    try:
        email = request.session['email']
    except Exception as e:
        return redirect('/')
    cursor = connection.cursor()
    cursor.execute("set search_path to hiday")
    cursor.execute("select * from akun where email='"+email+"'")
    pengguna = namedtuplefetchall(cursor)

    role = cekRole(email)
    roleAdmin = False
    rolePengguna = False
    if (role == 'Admin'):
        roleAdmin = True
    if (role == 'Pengguna'):
        rolePengguna = True
        
    if (roleAdmin):
        cursor.execute("select * from admin where email='"+email+"'")
        admin = namedtuplefetchall(cursor)
        email = admin[0].email

        argument = {
            'nama_akun' : email.split("@", 1)[0],
            'email' : email,
            'role' : role,
            'roleAdmin' : roleAdmin,
            'rolePengguna' : rolePengguna
        }
    elif (rolePengguna):
        cursor.execute("select * from pengguna where email='"+email+"'")
        pengguna = namedtuplefetchall(cursor)
        email = pengguna[0].email
        nama_area_pertanian = pengguna[0].nama_area_pertanian
        xp = pengguna[0].xp
        koin = pengguna[0].koin
        level = pengguna[0].level
        
        argument = {
            'nama_akun' : email.split("@", 1)[0],
            'email' : email,
            'role' : role,
            'roleAdmin' : roleAdmin,
            'rolePengguna' : rolePengguna,
            'nama_area_pertanian' : nama_area_pertanian,
            'xp' : xp,
            'koin' : koin,
            'level' : level
        }
    cursor.close()
    return render(request, "profil.html", argument)

    
def cekRole(email):
    cursor = connection.cursor()
    cursor.execute("set search_path to hiday")
    cursor.execute("select * from admin where email='"+email+"'")
    admin = namedtuplefetchall(cursor)
    if (admin != []):
        cursor.close()
        return "Admin"
    else:
        cursor.execute("select * from pengguna where email='"+email+"'")
        pengguna = namedtuplefetchall(cursor)
        if (pengguna != []):
            cursor.close()
            return "Pengguna"


def register(request):
    formulir = ChoiceRoleForm()
    argument = { 
        'form' : formulir,
        'formrole' : True,
        'roleAdmin' : False,
        'rolePengguna' : False
    }
    return render(request, 'registerPengguna.html', argument)

def registerPenggunaRole(request, message="", role=None):
    try:
        Role = str(request.POST['Role'])
    except:
        Role = role
        
    roleAdmin = False
    rolePengguna = False
    if(Role == "Admin"):
        formulir = AdminRoleForm()
        roleAdmin = True
    elif(Role == "Pengguna"):
        formulir = PenggunaRoleForm()
        rolePengguna = True

    argument = { 
        'form' : formulir,
        'role' : Role,
        'roleAdmin' : roleAdmin,
        'rolePengguna' : rolePengguna,
        'message': message
    }
    return render(request, 'registerPengguna.html', argument)


def insertAdmin(request):
    email = str(request.POST['email'])
    password = str(request.POST['password'])

    cursor = connection.cursor()
    cursor.execute("set search_path to hiday")
    cursor.execute("select * from akun where email='"+email+"'")
    hasil = namedtuplefetchall(cursor)
    if (hasil == []):
        cursor.execute("insert into akun values ('"+email+"')")
        cursor.execute("insert into admin values ('"+email+"','"+password+"')")
        
    else:
        cursor.close()
        return registerPenggunaRole(request, "Email sudah digunakan", 'Admin')
            
                
    cursor.execute("select * from admin where email='"+email+"' and password='"+password+"'")
    hasil = namedtuplefetchall(cursor)

    if (hasil == []):
        cursor.close()
        return index(request, False)
    else:
        cursor.execute("set search_path to public")
        request.session['email'] = hasil[0].email
        request.session['password'] = hasil[0].password
        request.session.set_expiry(1800)
        request.session['role'] = 'Admin'
        argument = {
            'nama_akun' : email.split("@", 1)[0],
            'hasil' : hasil,
            'roleAdmin' : True,
            'rolePengguna' : False,
        }
        cursor.close()
        return render(request, "home.html", argument)


def insertPengguna(request):
    email = str(request.POST['email'])
    password = str(request.POST['password'])
    nama_area_pertanian = str(request.POST['nama_area_pertanian'])
    xp = str(0)
    koin = str(0)
    level = str(1)

    cursor = connection.cursor()
    cursor.execute("set search_path to hiday")

    cursor.execute("select * from akun where email='"+email+"'")
    hasil = namedtuplefetchall(cursor)
    if (hasil != []):
        cursor.close()
        return registerPenggunaRole(request, "Email sudah digunakan", "Pengguna")
    
    cursor.execute("insert into akun values ('"+email+"')")
    cursor.execute("insert into pengguna values ('"+email+"','"+password+"','"+nama_area_pertanian+"','"+xp+"','"+koin+"','"+level+"')")
                
    cursor.execute("select * from pengguna where email='"+email+"' and password='"+password+"'")
    hasil = namedtuplefetchall(cursor)

    if (hasil == []):
        cursor.close()
        return index(request, False)
    else:
        cursor.execute("set search_path to public")
        request.session['email'] = hasil[0].email
        request.session['password'] = hasil[0].password
        request.session['nama_area_pertanian'] = hasil[0].nama_area_pertanian
        request.session['xp'] = 0
        request.session['koin'] = 0
        request.session['level'] = 1
        request.session.set_expiry(1800)
        request.session['role'] = 'Pengguna'
        argument = {
            'nama_akun' : email.split("@", 1)[0],
            'hasil' : hasil,
            'roleAdmin' : False,
            'rolePengguna' : True,
        }
        cursor.close()
        return render(request, "home.html", argument)
    
def lihatIsiLumbung(request):
    try:
        email = request.session['email']
    except Exception as e:
        return redirect('/')
    cursor = connection.cursor()
    cursor.execute("set search_path to hiday")
    cursor.execute("select * from akun where email='"+email+"'")
    pengguna = namedtuplefetchall(cursor)

    role = cekRole(email)
    roleAdmin = False
    rolePengguna = False
    if (role == 'Admin'):
        roleAdmin = True
    if (role == 'Pengguna'):
        rolePengguna = True
        
    if (roleAdmin):
        cursor.execute("select * from admin where email='"+email+"'")
        admin = namedtuplefetchall(cursor)
        email = admin[0].email

        cursor.execute("""select l.email,id_produk, p.nama, p.harga_jual, p.sifat_produk, lmp.jumlah
                from lumbung l, lumbung_memiliki_produk lmp, produk p
                where l.email = lmp.id_lumbung
                and lmp.id_produk = p.id
                and id_produk like 'HP%' order by id_produk,l.email""")
        hasil_panen = namedtuplefetchall(cursor)
        
        cursor.execute("""select l.email,id_produk, p.nama, p.harga_jual, p.sifat_produk, lmp.jumlah
                from lumbung l, lumbung_memiliki_produk lmp, produk p
                where l.email = lmp.id_lumbung
                and lmp.id_produk = p.id
                and id_produk like 'PH%' order by id_produk,l.email""")

login/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="UTF-8">
    <title>HI DAY E06 | 
    {% block title %}
    {% endblock title %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}">
    {% block meta %}
    {% endblock meta %}
</head>
<body>
  <nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
      <a class="navbar-brand" href="">
        <img src="{% static 'images/favicon.png' %}" height="32px" alt="" class="d-inline-block align-top">
          <b class="my-auto">HI DAY!</b>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto my-2 my-lg-0">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Lumbung
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'authentication:lihatIsiLumbung' %}">Lihat Isi Lumbung</a>
                  {% if request.session.role == "Pengguna" %}
                  <a class="dropdown-item" href="{% url 'upgrade-lumbung' %}">Upgrade Lumbung</a>
                  {% endif %}
                  <a class="dropdown-item" href="{% url 'transaksi-upgrade-lumbung' %}">List Transaksi Upgrade Lumbung</a>
                </div>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Koin
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% if request.session.role == "Admin" %}
                    <a class="dropdown-item" href="{% url 'buat-paket-koin' %}">Buat Paket Koin</a>
                    {% endif %}
                  <a class="dropdown-item" href="{% url 'paket-koin' %}">List Paket Koin</a>
                  <a class="dropdown-item" href="{% url 'transaksi-pembelian-koin' %}">List Transaksi Pembelian Koin</a>
                </div>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Aset
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% if request.session.role == "Admin" %}
                  <a class="dropdown-item" href="{% url 'aset:create_aset' %}">Buat Aset</a>                 
                  <a class="dropdown-item" href="{% url 'aset:read_aset' %}">List Aset</a>
                  <a class="dropdown-item" href="#">Buat Hewan Menghasilkan Produk Hewan</a>
                  <a class="dropdown-item" href="#">List Hewan Menghasilkan Produk Hewan</a>                 
                  <a class="dropdown-item" href="#">Buat Bibit Menghasilkan Panen</a>
                  <a class="dropdown-item" href="#">List Bibit Menghasilkan Panen</a>
                  {% endif %}
                  {% if request.session.role == "Pengguna" %}               
                  <a class="dropdown-item" href="{% url 'aset:read_aset' %}">List Aset</a>
                  <a class="dropdown-item" href="#">List Hewan Menghasilkan Produk Hewan</a>                 
                  <a class="dropdown-item" href="#">List Bibit Menghasilkan Panen</a>
                  {% endif %}
                </div>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Koleksi Aset
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% if request.session.role == "Admin" %}
                    <a class="dropdown-item" href="{% url 'koleksi_aset:read_koleksi_aset' %}">List Koleksi Aset</a>                 
                    <a class="dropdown-item" href="{% url 'transaksi_pembelian:read_transaksi_pembelian_aset' %}">List Transaksi Pembelian Aset</a>
                  {% endif %}
                  {% if request.session.role == "Pengguna" %}               
                    <a class="dropdown-item" href="{% url 'koleksi_aset:read_koleksi_aset' %}">List Koleksi Aset</a>        
                    <a class="dropdown-item" href="{% url 'transaksi_pembelian:create_transaksi_pembelian_aset' %}">Buat Transaksi Pembelian Aset</a>                 
                    <a class="dropdown-item" href="{% url 'transaksi_pembelian:read_transaksi_pembelian_aset' %}">List Transaksi Pembelian Aset</a>
                  {% endif %}
                </div>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Produk
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% if request.session.role == "Admin" %}
                    <a class="dropdown-item" href="{% url 'produk:createProduk' %}">Buat Produk</a>                 
                    <a class="dropdown-item" href="{% url 'produk:produk' %}">List Produk</a>
                    <a class="dropdown-item" href="{% url 'produk:createProduksi' %}">Buat Produksi</a>        
                    <a class="dropdown-item" href="{% url 'produk:produksi' %}">List Produksi</a>         
                  {% endif %}
                  {% if request.session.role == "Pengguna" %}                            
                    <a class="dropdown-item" href="{% url 'produk:produk' %}">List Produk</a>     
                    <a class="dropdown-item" href="{% url 'produk:produksi' %}">List Produksi</a>  
                  {% endif %}
                </div>
              </li>

              {% if request.session.role == "Admin" %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Histori Produksi
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">List Histori Produksi Hewan</a>                 
                  <a class="dropdown-item" href="{% url 'histori-produksi-tanaman' %}">List Histori Produksi Tanaman</a>
                  <a class="dropdown-item" href="#">List Histori Produksi Makanan</a>             
                </div>
              </li>
              {% endif %}
              {% if request.session.role == "Pengguna" %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Proses Produksi
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="">Produksi Hewan</a>                 
                  <a class="dropdown-item" href="#">List Histori Produksi Hewan</a>
                  <a class="dropdown-item" href="{% url 'produksi-tanaman' %}">Produksi Tanaman</a>    
                  <a class="dropdown-item" href="{% url 'histori-produksi-tanaman' %}">List Histori Produksi Tanaman</a>
                  <a class="dropdown-item" href="#">Produksi Produk Makanan</a>   
                  <a class="dropdown-item" href="{% url 'produk:historiProduksiMakanan' %}">List Histori Produksi Makanan</a> 
                </div>
              </li>
              {% endif %}

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Pesanan
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% if request.session.role == "Admin" %}
                  <a class="dropdown-item" href="#">Buat Pesanan</a>                       
                  {% endif %}                    
                  <a class="dropdown-item" href="#">List Pesanan</a>     
                  <a class="dropdown-item" href="#">List Histori Penjualan</a>  

                </div>
              </li>
      <div class="row justify-items-end">
        <div style="width: 20px;"></div>
        <a href="{% url 'authentication:logout' %}" class="mybutton">Log Out</a>
      </div>
    </div>
  </nav>
  <nav></nav>
{% block content %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  
</body>
</html>

login/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Home
{% endblock title %}


{% block content %}
    <div class="container-fluid header">
        <div class="container">
            <h1 class="welcome">Welcome to <b>HI DAY E06</b>,</h1>
            <h1>{{nama_akun}}</h1>
            <a href="{% url 'authentication:profil' %}" class="mybutton butwhite" role="button">My Profile</a>
            {% if rolePengguna%}
            <a href="{% url 'authentication:lihatIsiLumbung' %}" class="mybutton butwhite" role="button">My Lumbung</a>
            {% elif roleAdmin%}
            <a href="{% url 'authentication:lihatIsiLumbung' %}" class="mybutton butwhite" role="button">Lumbung</a>
            {% endif %}
        </div>
    </div>
{% endblock content %}