aset/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "aset"

urlpatterns = [
    path('read/', views.read_aset, name='read_aset'),
    path('read/dekorasi/', views.read_dekorasi, name='read_dekorasi'),
    path('read/bibit-tanaman/', views.read_bibit_tanaman, name='read_bibit_tanaman'),
    path('read/hewan/', views.read_hewan, name='read_hewan'),
    path('read/kandang/', views.read_kandang, name='read_kandang'),
    path('read/alat-produksi/', views.read_alat_produksi, name='read_alat_produksi'),
    path('read/petak-sawah/', views.read_petak_sawah, name='read_petak_sawah'),
    path('create/', views.create_aset, name='create_aset'),
    path('create/dekorasi/', views.create_dekorasi, name='create_dekorasi'),
    path('create/bibit-tanaman/', views.create_bibit_tanaman, name='create_bibit_tanaman'),
    path('create/hewan/', views.create_hewan, name='create_hewan'),
    path('create/kandang/', views.create_kandang, name='create_kandang'),
    path('create/alat-produksi/', views.create_alat_produksi, name='create_alat_produksi'),
    path('create/petak-sawah/', views.create_petak_sawah, name='create_petak_sawah'),
    path('form_update_dekorasi/<str:id>/', views.formUpdateDekorasi, name='formUpdateDekorasi'),
    path('update/dekorasi/', views.updateDekorasi, name='updateDekorasi'),
    path('form_update_bibit_tanaman/<str:id>/', views.formUpdateBibitTanaman, name='formUpdateBibitTanaman'),
    path('update/bibit-tanaman/', views.updateBibitTanaman, name='updateBibitTanaman'),
    path('form_update_kandang/<str:id>/', views.formUpdateKandang, name='formUpdateKandang'),
    path('update/kandang/', views.updateKandang, name='updateKandang'),
    path('form_update_hewan/<str:id>/', views.formUpdateHewan, name='formUpdateHewan'),
    path('update/hewan/', views.updateHewan, name='updateHewan'),
    path('form_update_alat_produksi/<str:id>/', views.formUpdateAlatProduksi, name='formUpdateAlatProduksi'),
    path('update/alat-produksi/', views.updateAlatProduksi, name='updateAlatProduksi'),
    path('form_update_petak_sawah/<str:id>/', views.formUpdatePetakSawah, name='formUpdatePetakSawah'),
    path('delete/dekorasi/<str:id>/', views.deleteDekorasi, name='deleteDekorasi'),
    path('delete/bibit-tanaman/<str:id>/', views.deleteBibitTanaman, name='deleteBibitTanaman'),
    path('delete/kandang/<str:id>/', views.deleteKandang, name='deleteKandang'),
    path('delete/hewan/<str:id>/', views.deleteHewan, name='deleteHewan'),
    path('delete/alat-produksi/<str:id>/', views.deleteAlatProduksi, name='deleteAlatProduksi'),
    path('delete/petak-sawah/<str:id>/', views.deletePetakSawah, name='deletePetakSawah'),
]

produk/urls.py
from django.urls import path

from .views import viewsProduk,viewsProduksi,viewsHistoriProduksiMakanan, createProduk, updateProduk, formUpdateProduk, deleteProduk, createProduksi,deleteProduksi

app_name ='produk'

urlpatterns = [
    path('form_create_produk/', createProduk, name='createProduk'),
    path('read_produk/', viewsProduk, name='produk'),
    path('form_update_produk/<str:id>/', formUpdateProduk, name='formUpdateProduk'),
    path('update_produk/', updateProduk, name='updateProduk'),   
    path('delete_produk/<str:id>/', deleteProduk, name='deleteProduk'), 
     
    path('form_create_produksi/', createProduksi, name='createProduksi'),
    path('read_produksi/', viewsProduksi, name='produksi'),
    # path('form_update_produksi/<str:id>/', formUpdateProduksi, name='formUpdateProduksi'),
    # path('update_produk/', updateProduksi, name='updateProduksi'),
    path('delete_produksi/<str:id>/', deleteProduksi, name='deleteProduksi'),
    
    # path('form_create_histori_produksi_makanan/', createHistoriProduksiMakanan, name='createHistoriProduksiMakanan'),
    path('read_histori_produksi_makanan/', viewsHistoriProduksiMakanan, name='historiProduksiMakanan'),
    
]

tk_e06/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('aset/', include('aset.urls')),
    path('koleksi-aset/', include('koleksi_aset.urls')),
    path('transaksi-pembelian/', include('transaksi_pembelian.urls')),
    path('paket-koin/', include('paket_koin.urls')),
    path('lumbung/', include('lumbung.urls')),
    path('produk/', include('produk.urls')),
    path('', include('histori.urls')),
]

aset/models.py
from django.db import models

# Create your models here.

aset/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.db import connection
from collections import namedtuple
from login.views import namedtuplefetchall, cekRole
from .forms import CreateDekorasiForm, CreateBibitTanamanForm, CreateKandangForm, CreateHewanForm, CreateAlatProduksiForm, CreatePetakSawahForm, UpdateDekorasiForm, UpdateBibitTanamanForm, UpdateKandangForm, UpdateHewanForm, UpdateAlatProduksiForm, UpdatePetakSawahForm

def read_aset(request):
    return render(request, 'read_aset.html')

def read_dekorasi(request):
    cursor = connection.cursor()
    cursor.execute("set search_path to public")
    try:
        Role = request.session['role']
    except:
        return redirect('/')
    cursor.execute("set search_path to hiday")
    cursor.execute(f"""select *,
                    case
	                    when not exists(select * from koleksi_aset_memiliki_aset kama where kama.id_aset = dekorasi.id_aset) and
                        not exists(select * from dekorasi_memiliki_histori_penjualan dmhp where dmhp.id_dekorasi = dekorasi.id_aset)
                    then 1 else 0 end as can_delete
                    from aset join dekorasi on dekorasi.id_aset = aset.id
                    where aset.id like 'DK%'""")
    hasil = namedtuplefetchall(cursor)

    data = {
            'list_dekorasi' : hasil,
    }

    roleAdmin = False
    rolePengguna = False

    if Role == "Admin":
        roleAdmin = True
    elif Role == "Pengguna":
        rolePengguna = True

    data = {
        'list_dekorasi' : hasil,
        'roleAdmin' : roleAdmin,
        'rolePengguna' : rolePengguna,
    }

    return render(request, "read_dekorasi.html", data) 

def read_bibit_tanaman(request):
    cursor = connection.cursor()
    cursor.execute("set search_path to public")
    try:
        Role = request.session['role']
    except:
        return redirect('/')
    cursor.execute("set search_path to hiday")
    cursor.execute(f"""select id_aset, nama, minimum_level, harga_beli, CAST(extract(epoch from durasi_panen::interval) / 60 AS int) durasi_panen,
                    case
                        when not exists(select * from koleksi_aset_memiliki_aset kama where kama.id_aset = bibit_tanaman.id_aset) and 
                        not exists(select * from bibit_tanaman_menghasilkan_hasil_panen btmhp where btmhp.id_bibit_tanaman = bibit_tanaman.id_aset) and 
                        not exists(select * from histori_tanaman ht where ht.id_bibit_tanaman = bibit_tanaman.id_aset) 
                    then 1 else 0 end as can_delete
                    from aset join bibit_tanaman on bibit_tanaman.id_aset = aset.id
                    where aset.id like 'BT%'""")
    hasil = namedtuplefetchall(cursor)

    roleAdmin = False
    rolePengguna = False

    if Role == "Admin":
        roleAdmin = True
    elif Role == "Pengguna":
        rolePengguna = True

    data = {
        'list_bibit_tanaman' : hasil,
        'roleAdmin' : roleAdmin,
        'rolePengguna' : rolePengguna,
    }

    return render(request, "read_bibit_tanaman.html", data)

def read_kandang(request):
    cursor = connection.cursor()
    cursor.execute("set search_path to public")
    try:
        Role = request.session['role']
    except:
        return redirect('/')
    cursor.execute("set search_path to hiday")
    cursor.execute(f"""select *,
                    case
	                    when not exists(select * from koleksi_aset_memiliki_aset kama where kama.id_aset = kandang.id_aset)
                    then 1 else 0 end as can_delete
                    from aset join kandang on kandang.id_aset = aset.id
                    where aset.id like 'KD%'""")
    hasil = namedtuplefetchall(cursor)

    roleAdmin = False
    rolePengguna = False

    if Role == "Admin":
        roleAdmin = True
    elif Role == "Pengguna":
        rolePengguna = True
    
    data = {
        'list_kandang' : hasil,
        'roleAdmin' : roleAdmin,
        'rolePengguna' : rolePengguna,
    }

    return render(request, "read_kandang.html", data)

def read_hewan(request):
    cursor = connection.cursor()
    cursor.execute("set search_path to public")
    try:
        Role = request.session['role']
    except:
        return redirect('/')
    cursor.execute("set search_path to hiday")
    cursor.execute(f"""select id_aset, nama, minimum_level, harga_beli, CAST(extract(epoch from durasi_produksi::interval) / 60 AS int) durasi_produksi, id_kandang,
                    case
	                    when not exists(select * from koleksi_aset_memiliki_aset kama where kama.id_aset = hewan.id_aset) and 
                        not exists(select * from hewan_menghasilkan_produk_hewan hmph where hmph.id_hewan = hewan.id_aset) and 
                        not exists(select * from histori_hewan hh where hh.id_hewan = hewan.id_aset)
                    then 1 else 0 end as can_delete
                    from aset join hewan on hewan.id_aset = aset.id
                    where aset.id like 'HW%'""")
    hasil = namedtuplefetchall(cursor)

    roleAdmin = False
    rolePengguna = False

    if Role == "Admin":
        roleAdmin = True
    elif Role == "Pengguna":
        rolePengguna = True

    data = {
        'list_hewan' : hasil,
        'roleAdmin' : roleAdmin,
        'rolePengguna' : rolePengguna,
    }

    return render(request, "read_hewan.html", data)

def read_alat_produksi(request):
    cursor = connection.cursor()
    cursor.execute("set search_path to public")
    try:
        Role = request.session['role']
    except:
        return redirect('/')
    cursor.execute("set search_path to hiday")
    cursor.execute(f"""select *,
                    case
	                    when not exists(select * from koleksi_aset_memiliki_aset kama where kama.id_aset = alat_produksi.id_aset) and 
                        not exists(select * from produksi p where p.id_alat_produksi = alat_produksi.id_aset)
                    then 1 else 0 end as can_delete
                    from aset join alat_produksi on alat_produksi.id_aset = aset.id
                    where aset.id like 'AP%'""")
    hasil = namedtuplefetchall(cursor)

    roleAdmin = False
    rolePengguna = False

    if Role == "Admin":
        roleAdmin = True
    elif Role == "Pengguna":
        rolePengguna = True
    
    data = {
        'list_alat_produksi' : hasil,
        'roleAdmin' : roleAdmin,
        'rolePengguna' : rolePengguna,
    }

    return render(request, "read_alat_produksi.html", data)

def read_petak_sawah(request):
    cursor = connection.cursor()
    cursor.execute("set search_path to public")
    try:
        Role = request.session['role']
    except:
        return redirect('/')
    cursor.execute("set search_path to hiday")
    cursor.execute(f"""select *,
                    case
	                    when not exists(select * from koleksi_aset_memiliki_aset kama where kama.id_aset = petak_sawah.id_aset)
                    then 1 else 0 end as can_delete
                    from aset join petak_sawah on petak_sawah.id_aset = aset.id
                    where aset.id like 'PS%'""")
    hasil = namedtuplefetchall(cursor)

    roleAdmin = False
    rolePengguna = False

    if Role == "Admin":
        roleAdmin = True
    elif Role == "Pengguna":
        rolePengguna = True
    
    data = {
        'list_petak_sawah' : hasil,
        'roleAdmin' : roleAdmin,
        'rolePengguna' : rolePengguna,
    }

    return render(request, "read_petak_sawah.html", data)

def create_aset(request):
    return render(request, 'create_aset.html')

def get_input_dekorasi(request):
    input = request.POST
    nama = input['nama']
    minimum_level = input['minimum_level']
    harga_beli = input['harga_beli']
    harga_jual = input['harga_jual']
    return [nama, minimum_level, harga_beli, harga_jual]

def create_dekorasi(request):
    message =""
    cursor = connection.cursor()
    cursor.execute("set search_path to hiday")
    cursor.execute("select id as c from aset where id like 'DK%' order by id asc")
    id_aset = namedtuplefetchall(cursor)
    print(id_aset)
    id_aset = id_aset[-1].c
    
    id_aset = int(id_aset[2:])
    id_aset = int(id_aset) + 1
    id_dekorasi = "DK"+f"{id_aset:03d}"
    
    if request.method == 'POST':
        input = get_input_dekorasi(request)
        try:
            cursor.execute("insert into aset values ('"+id_dekorasi+"','"+input[0]+"','"+input[1]+"','"+input[2]+"')")
            cursor.execute("insert into dekorasi values ('"+id_dekorasi+"','"+input[3]+"')")
            cursor.close()
            return redirect('/aset/read/dekorasi/')
        except:
           message = "Data tidak berhasil dibuat"


    form = CreateDekorasiForm(initial={'id':id_dekorasi})
    
    data = {
        'form': form,
        'message' : message
    }

    return render(request, "create_dekorasi.html", data)

def get_input_bibit_tanaman(request):
    input = request.POST
    nama = input['nama']
    minimum_level = input['minimum_level']
    harga_beli = input['harga_beli']
    durasi_panen = input['durasi_panen']
    return [nama, minimum_level, harga_beli, durasi_panen]

def create_bibit_tanaman(request):
    message =""
    cursor = connection.cursor()
    cursor.execute("set search_path to hiday")
    cursor.execute("select id as c from aset where id like 'BT%' order by id asc")
    id_aset = namedtuplefetchall(cursor)
    id_aset = id_aset[-1].c
    
    id_aset = int(id_aset[2:])
    id_aset = int(id_aset) + 1
    id_bibit_tanaman= "BT"+f"{id_aset:03d}"
        
    if request.method == 'POST':
        input = get_input_bibit_tanaman(request)
        durasi = int(input[3])
        s = durasi*60
        format_durasi = '{:02}:{:02}:{:02}'.format(s//3600, s%3600//60, s%60)
        try:
            cursor.execute("insert into aset values ('"+id_bibit_tanaman+"','"+input[0]+"','"+input[1]+"','"+input[2]+"')")

aset/templates/create_aset.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Create Aset
{% endblock title %}

{% block content %}
<head>
  <meta charset="UTF-8">
    <title>HI DAY | Buat Aset
    </title>
</head>
<body>
  <div class="container justify-content-center align-items-center">
    <h1 class="list_title">Menu Buat Aset</h1>
    <div style="text-align:center">
      <a class="btn btn-primary" style="margin:10px;" href="{% url 'aset:create_dekorasi' %}">Dekorasi</a>
    </div>
    <div style="text-align:center">
      <a class="btn btn-primary" style="margin:10px;" href="{% url 'aset:create_bibit_tanaman' %}">Bibit Tanaman</a>
    </div>
    <div style="text-align:center">
      <a class="btn btn-primary" style="margin:10px;" href="{% url 'aset:create_kandang' %}">Kandang</a>
    </div>
    <div style="text-align:center">
      <a class="btn btn-primary" style="margin:10px;" href="{% url 'aset:create_hewan' %}">Hewan</a>
    </div>
    <div style="text-align:center">
      <a class="btn btn-primary" style="margin:10px;" href="{% url 'aset:create_alat_produksi' %}">Alat Produksi</a>
    </div>
    <div style="text-align:center">
      <a class="btn btn-primary"style="margin:10px;" href="{% url 'aset:create_petak_sawah' %}">Petak Sawah</a>
    </div>
</div>
</body>
{% endblock content %}

aset/templates/create_bibit_tanaman.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Create Aset Bibit Tanaman
{% endblock title %}


{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  function validateForm() {
    var data = document.forms["myForm"]["formBibitTanaman"].value;
    if (data == "" ) {
      alert("“Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu.");
      return false;
    }
  }
</script>
<div class="container justify-content-center align-items-center">
  <h1 class="list_title">Form Buat Aset Bibit Tanaman</h1>
  <h2 class="message">{{message}}</h2>
  <br>
  <div class="row justify-content-center">
    <div class="login">      
      <form  method="POST" action="{% url 'aset:create_bibit_tanaman' %}" onsubmit="return validateForm()" method="post" required>
        {% csrf_token %}
        <div class="loginForm" name="formBibitTanaman">{{ form.as_p }}</div>
        <br>
        <input type="submit" value="Create" name="tombol">
      </form>
      
    </div>
  </div>
</div>
{% endblock content %}

aset/templates/create_dekorasi.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Create Aset Dekorasi
{% endblock title %}


{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  function validateForm() {
    var data = document.forms["myForm"]["formDekorasi"].value;
    if (data == "" ) {
      alert("“Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu.");
      return false;
    }
  }
</script>
<div class="container justify-content-center align-items-center">
  <h1 class="list_title">Form Buat Aset Dekorasi</h1>
  <h2 class="message">{{message}}</h2>
  <br>
  <div class="row justify-content-center">
    <div class="login">      
      <form  method="POST" action="{% url 'aset:create_dekorasi' %}" onsubmit="return validateForm()" method="post" required>
        {% csrf_token %}
        <div class="loginForm" name="formDekorasi">{{ form.as_p }}</div>
        <br>
        <input type="submit" value="Tambahkan" name="tombol">
      </form>
      
    </div>
  </div>
</div>
{% endblock content %}

aset/templates/read_alat_produksi.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Read Aset Alat Produksi
{% endblock title %}


{% block content %}
<div class="container justify-content-center align-items-center">
    <h1 class="list_title">List Alat Produksi</h1>
    <h2 class="message">{{message}}</h2>
    <div class="row justify-content-center">
        <table class="table table-hover table-striped text-center">
            <thead>
                <tr>
                    <th scope="col">No</th>
                    <th scope="col">ID Aset</th>
                    <th scope="col">Nama</th>
                    <th scope="col">Minimum Level</th>
                    <th scope="col">Harga Beli</th>
                    <th scope="col">Kapasitas Maks</th>
                    {% if roleAdmin %}
                        <th scope="col">Action</th>
                    {% endif %} 
                </tr>
            </thead>
            <tbody>
            {%for row in list_alat_produksi %}
                <tr class="table-striped">
                <th scope="row">{{forloop.counter}}</th>
                <td>{{row.id_aset}}</td>
                <td>{{row.nama}}</td>
                <td>{{row.minimum_level}}</td>
                <td>{{row.harga_beli}}</td>
                <td>{{row.kapasitas_maks}}</td>
                {% if roleAdmin %}
                <td>
                    <a href="{% url 'aset:formUpdateAlatProduksi' row.id %}" class="mybutton butwhite" role="button">UPDATE</a>
                    <br>
                    {% if row.can_delete %}
                    <a href="{% url 'aset:deleteAlatProduksi' row.id %}" class="mybutton butred" role="button">DELETE</a>
                    {% endif %}
                </td>
                {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table> 
    </div>
</div>
{% endblock content %}

aset/templates/read_aset.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Read Aset
{% endblock title %}

{% block content %}
<head>
  <meta charset="UTF-8">
    <title>HI DAY | Lihat Aset
    </title>
</head>
<body>
  <div class="container justify-content-center align-items-center">
    <h1 class="list_title">Menu Lihat Aset</h1>
    <div style="text-align:center">
      <a class="btn btn-primary" style="margin:10px;" href="{% url 'aset:read_dekorasi' %}">Dekorasi</a>
    </div>
    <div style="text-align:center">
      <a class="btn btn-primary" style="margin:10px;" href="{% url 'aset:read_bibit_tanaman' %}">Bibit Tanaman</a>
    </div>
    <div style="text-align:center">
      <a class="btn btn-primary" style="margin:10px;" href="{% url 'aset:read_kandang' %}">Kandang</a>
    </div>
    <div style="text-align:center">
      <a class="btn btn-primary" style="margin:10px;" href="{% url 'aset:read_hewan' %}">Hewan</a>
    </div>
    <div style="text-align:center">
      <a class="btn btn-primary" style="margin:10px;" href="{% url 'aset:read_alat_produksi' %}">Alat Produksi</a>
    </div>
    <div style="text-align:center">
      <a class="btn btn-primary"style="margin:10px;" href="{% url 'aset:read_petak_sawah' %}">Petak Sawah</a>
    </div>
</div>
</body>
{% endblock content %}

aset/templates/read_bibit_tanaman.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Read Aset Bibit Tanaman
{% endblock title %}


{% block content %}
<div class="container justify-content-center align-items-center">
    <h1 class="list_title">List Bibit Tanaman</h1>
    <h2 class="message">{{message}}</h2>

    <div class="row justify-content-center">
        <!-- {% if roleAdmin%}
        <a href="{% url 'produk:createProduk' %}" class="mybutton" role="button" style="margin-bottom: 30px;">Create Item</a>
        {% endif %}  -->
        <table class="table table-hover table-striped text-center">
            <thead>
                <tr>
                    <th scope="col">No</th>
                    <th scope="col">ID Aset</th>
                    <th scope="col">Nama</th>
                    <th scope="col">Minimum Level</th>
                    <th scope="col">Harga Beli</th>
                    <th scope="col">Durasi Panen</th>
                    {% if roleAdmin %}
                        <th scope="col">Action</th>
                    {% endif %} 
                </tr>
            </thead>
            <tbody>
            {%for row in list_bibit_tanaman %}
                <tr class="table-striped">
                <th scope="row">{{forloop.counter}}</th>
                <td>{{row.id_aset}}</td>
                <td>{{row.nama}}</td>
                <td>{{row.minimum_level}}</td>
                <td>{{row.harga_beli}}</td>
                <td>{{row.durasi_panen}} menit </td>
                {% if roleAdmin %}
                <td>
                    <a href="{% url 'aset:formUpdateBibitTanaman' row.id_aset %}" class="mybutton butwhite" role="button">UPDATE</a>
                    <br>
                    {% if row.can_delete %}
                    <a href="{% url 'aset:deleteBibitTanaman' row.id_aset %}" class="mybutton butred" role="button">DELETE</a>
                    {% endif %}
                </td>
                {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table> 
    </div>
</div>
{% endblock content %}

aset/templates/read_dekorasi.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Read Aset Dekorasi
{% endblock title %}


{% block content %}
<div class="container justify-content-center align-items-center">
    <h1 class="list_title">List Dekorasi</h1>
    <h2 class="message">{{message}}</h2>

    <div class="row justify-content-center">
        <!-- {% if roleAdmin%}
        <a href="{% url 'produk:createProduk' %}" class="mybutton" role="button" style="margin-bottom: 30px;">Create Item</a>
        {% endif %}  -->
        <table class="table table-hover table-striped text-center">
            <thead>
                <tr>
                    <th scope="col">No</th>
                    <th scope="col">ID Aset</th>
                    <th scope="col">Nama</th>
                    <th scope="col">Minimum Level</th>
                    <th scope="col">Harga Beli</th>
                    <th scope="col">Harga Jual</th>
                    {% if roleAdmin %}
                    <th scope="col">Action</th>
                    {% endif %} 
                </tr>
            </thead>
            <tbody>
            {%for row in list_dekorasi %}
                <tr class="table-striped">
                <th scope="row">{{forloop.counter}}</th>
                <td>{{row.id_aset}}</td>
                <td>{{row.nama}}</td>
                <td>{{row.minimum_level}}</td>
                <td>{{row.harga_beli}}</td>
                <td>{{row.harga_jual}}</td>
                {% if roleAdmin %}
                <td>
                    <a href="{% url 'aset:formUpdateDekorasi' row.id %}" class="mybutton butwhite" role="button">UPDATE</a>
                    <br>
                    {% if row.can_delete %}
                    <a href="{% url 'aset:deleteDekorasi' row.id %}" class="mybutton butred" role="button">DELETE</a>
                    {% endif %}
                </td>
                {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table> 
    </div>
</div>
{% endblock content %}

aset/templates/read_petak_sawah.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Read Aset Petak Sawah
{% endblock title %}


{% block content %}
<div class="container justify-content-center align-items-center">
    <h1 class="list_title">List Petak Sawah</h1>
    <h2 class="message">{{message}}</h2>

    <div class="row justify-content-center">
        <!-- {% if roleAdmin%}
        <a href="{% url 'produk:createProduk' %}" class="mybutton" role="button" style="margin-bottom: 30px;">Create Item</a>
        {% endif %}  -->
        <table class="table table-hover table-striped text-center">
            <thead>
                <tr>
                    <th scope="col">No</th>
                    <th scope="col">ID Aset</th>
                    <th scope="col">Nama</th>
                    <th scope="col">Minimum Level</th>
                    <th scope="col">Harga Beli</th>
                    <th scope="col">Jenis Tanaman</th>
                    {% if roleAdmin %}
                        <th scope="col">Action</th>
                    {% endif %} 
                </tr>
            </thead>
            <tbody>
            {%for row in list_petak_sawah %}
                <tr class="table-striped">
                <th scope="row">{{forloop.counter}}</th>
                <td>{{row.id_aset}}</td>
                <td>{{row.nama}}</td>
                <td>{{row.minimum_level}}</td>
                <td>{{row.harga_beli}}</td>
                <td>{{row.jenis_tanaman}}</td>
                {% if roleAdmin %}
                <td>
                    <a href="{% url 'aset:formUpdatePetakSawah' row.id %}" class="mybutton butwhite" role="button">UPDATE</a>
                    <br>
                    {% if row.can_delete %}
                    <a href="{% url 'aset:deletePetakSawah' row.id %}" class="mybutton butred" role="button">DELETE</a>
                    {% endif %}
                </td>
                {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table> 
    </div>
</div>
{% endblock content %}

aset/templates/update_dekorasi.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Update Aset Dekorasi
{% endblock title %}


{% block content %}
<div class="container justify-content-center align-items-center">
  <h1 class="list_title">Update Aset Dekorasi</h1>
  <h2 class="message">{{message}}</h2>

    <div class="row mainRow align-items-center justify-content-center">
      <div class="login">      
        <h2>Update Aset Dekorasi</h2>
        <br>
        <form  method="POST" action="/aset/update/dekorasi/">
          {% csrf_token %}
          {% for field in form.visible_fields %}
            <div class="loginForm">{{ field.label_tag }} {{ field }}</div>
          {% endfor %}
          <input type="submit" value="Simpan" name="tombol" class="mybutton">
        </form>
      </div>
    </div>
  </div>
{% endblock content %}